FROM microsoft/aspnetcore-build:latest

WORKDIR /app

COPY project.json .
RUN ["dotnet", "restore"]

COPY . /app
RUN ["dotnet", "publish", "-o", "/bin/dist", "-c", "release"]

EXPOSE 80/tcp

ENTRYPOINT ["dotnet", "/bin/dist/spd_cli.dll"]
