FROM microsoft/aspnetcore-build:latest

WORKDIR /app

COPY project.json .
RUN ["dotnet", "restore"]

COPY . /app
RUN ["dotnet", "publish", "--output", "/bin/dist"]

WORKDIR /bin/dist

EXPOSE 5000/tcp

ENTRYPOINT ["dotnet", "spd_cli"]
