FROM microsoft/dotnet:latest

RUN apt-get update
RUN apt-get install -y build-essential nodejs nodejs-legacy

WORKDIR /app

COPY project.json .
RUN ["dotnet", "restore"]

COPY . /app
RUN ["dotnet", "publish" "--output", "bin/dist"]

WORKDIR /app/bin/dist
EXPOSE 5000/tcp

ENTRYPOINT ["dotnet", "spd_cli.dll"]
